# Generated by Django 5.1.3 on 2024-11-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_moodlog_created_at_moodlog_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='content',
            new_name='entry',
        ),
    ]
