# Generated by Django 5.1.3 on 2024-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_content_journalentry_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='entry',
            new_name='content',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=100),
        ),
    ]
