# Generated by Django 5.1.3 on 2024-11-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_entry_journalentry_content_journalentry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypost',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='content',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
